spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/bhargav-raj-199/fullstack-repo.git
  application:
    name: MOBILE-STORE-CONFIG
    
eureka:
  client:
    service-url:
      default-zone: http://EUREKA-REGISTRY
  
    

          