spring:
  application:
    name: MOBILE-STORE-GET-SERVICE
  config:
    import: configserver:http://${confighost}:${configport}


eureka:
  client:
    service-url:
      default-zone: http://EUREKA-REGISTRY